version: "3.3"

services:
    db:
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: RootMaster123@!
            MYSQL_DATABASE: conalep
            MYSQL_USER: conalep
            MYSQL_PASSWORD: conalep
        volumes:
            - db:/var/lib/mysql
    
    laravel:
        restart: always
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - 8081:80


volumes:
    db: